services:
  zoro:
    container_name: zoro-ai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    volumes:
      - ./.env:/app/.env:ro
      - ./app/data/my_seed.json:/app/data/my_seed.json:ro
      - ./logs:/app/logs
      - ./app:/app
    environment:
      - CDP_API_KEY_NAME=${CDP_API_KEY_NAME}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
