export const player1 = {
  name: "Kevin De Bruyne",
  position: "CM",
  rating: 91,
  id: 1,
  club: "Manchester City",
  nationality: "Belgium",
  stats: {
    pace: 74,
    attack: 86,
    passing: 93,
    dribbling: 87,
    defence: 64,
    physical: 77,
  },
};

export const player2 = {
  name: "Lionel Messi",
  position: "RW",
  rating: 93,
  id: 2,

  club: "Paris Saint-Germain",
  nationality: "Argentina",
  stats: {
    pace: 80,
    attack: 92,
    passing: 91,
    dribbling: 95,
    defence: 34,
    physical: 65,
  },
};

export const player3 = {
  name: "Virgil van Dijk",
  position: "CB",
  rating: 89,
  club: "Liverpool",
  id: 3,

  nationality: "Netherlands",
  stats: {
    pace: 71,
    attack: 60,
    passing: 71,
    dribbling: 72,
    defence: 91,
    physical: 86,
  },
};

export const player4 = {
  name: "Kylian Mbappé",
  position: "ST",
  rating: 91,
  id: 4,
  club: "Paris Saint-Germain",
  nationality: "France",
  stats: {
    pace: 97,
    attack: 88,
    passing: 80,
    dribbling: 92,
    defence: 36,
    physical: 76,
  },
};

export const player5 = {
  name: "Neymar Jr",
  position: "LW",
  rating: 89,
  id: 5,

  club: "Paris Saint-Germain",
  nationality: "Brazil",
  stats: {
    pace: 87,
    attack: 83,
    passing: 86,
    dribbling: 93,
    defence: 37,
    physical: 61,
  },
};

export const player6 = {
  name: "Robert Lewandowski",
  position: "ST",
  rating: 91,
  id: 6,

  club: "Barcelona",
  nationality: "Poland",
  stats: {
    pace: 75,
    attack: 92,
    passing: 79,
    dribbling: 86,
    defence: 44,
    physical: 82,
  },
};

export const countryToCode: { [key: string]: string } = {
  england: "gb-eng",
  france: "fr",
  spain: "es",
  germany: "de",
  italy: "it",
  portugal: "pt",
  netherlands: "nl",
  belgium: "be",
  brazil: "br",
  argentina: "ar",
  "united states": "us",
  mexico: "mx",
  canada: "ca",
  japan: "jp",
  "south korea": "kr",
  australia: "au",
  nigeria: "ng",
  senegal: "sn",
  egypt: "eg",
  morocco: "ma",
  croatia: "hr",
  serbia: "rs",
  switzerland: "ch",
  poland: "pl",
  wales: "gb-wls",
  scotland: "gb-sct",
  ireland: "ie",
  sweden: "se",
  denmark: "dk",
  norway: "no",
  finland: "fi",
  iceland: "is",
  greece: "gr",
  turkey: "tr",
  russia: "ru",
  ukraine: "ua",
  cameroon: "cm",
  ghana: "gh",
  "ivory coast": "ci",
  algeria: "dz",
  tunisia: "tn",
  "saudi arabia": "sa",
  iran: "ir",
  iraq: "iq",
  qatar: "qa",
  "united arab emirates": "ae",
  china: "cn",
  austria: "at",
  romania: "ro",
  hungary: "hu",
  "czech republic": "cz",
  slovakia: "sk",
  slovenia: "si",
  bulgaria: "bg",
};
export const clubToId: { [key: string]: number } = {
  "Manchester United": 33,
  "Manchester City": 50,
  Liverpool: 40,
  Chelsea: 49,
  Arsenal: 42,
  Tottenham: 47,
  "Real Madrid": 541,
  Barcelona: 529,
  "Bayern Munich": 157,
  "Paris Saint-Germain": 85,
  Juventus: 496,
  "AC Milan": 489,
  Inter: 505,
  "Borussia Dortmund": 165,
  Ajax: 194,
  Porto: 212,
  Benfica: 211,
  "Atletico Madrid": 530,
  // Add more teams as needed
};
